version: "3.5"

services:
  # Database
  database:
    image: mongo:4.0.11
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    
  # Redis
  redis:
    image: redis:5-alpine
    restart: unless-stopped
    ports:
        - "16379:6379"
  
  # GraphQL
  api:
    build:
        context: .
        dockerfile: Dockerfile
    user: "node"
    restart: unless-stopped
    working_dir: /home/node/app
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
    environment:
      - NODE_ENV=development
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - DB_CONNECTION_STRING=mongodb://database/adonis-start-dev
    volumes:
      - ./:/home/node/app
    ports:
      - 3333:3333
    command: "yarn startup:dev"